'use client';
import { useEffect, useState } from 'react';

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Interaction='like'|'dislike'|'follow'|null;
type User={id:string;name:string;favorite_genres:string[]};
type Book={work_id:number;title:string;first_author?:string|null;description?:string|null;earliest_known_publication_year?:number|null;average_rating?:number|null;user_rating?:number|null;interaction?:Interaction};
type SearchResult={items:Book[];page:number;page_size:number;total:number;total_pages:number};

export default function Page(){
 const[users,setUsers]=useState<User[]>([]),[uid,setUid]=useState(''),[q,setQ]=useState(''),[suggestions,setSuggestions]=useState<Book[]>([]),[result,setResult]=useState<SearchResult|null>(null),[searchPage,setSearchPage]=useState(1),[showAll,setShowAll]=useState(false),[recommendation,setRecommendation]=useState(''),[recommendations,setRecommendations]=useState<Book[]>([]),[loading,setLoading]=useState(false),[recommendLoading,setRecommendLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{fetch(API+'/users').then(r=>r.json()).then(u=>{setUsers(u);if(u[0])setUid(u[0].id)}).catch(()=>setError('Could not connect to the application.'))},[]);
 useEffect(()=>{if(!q.trim()||showAll){setSuggestions([]);return}const timer=setTimeout(async()=>{setLoading(true);try{const r=await fetch(API+`/books/search?q=${encodeURIComponent(q)}&user_id=${uid}&page=1&page_size=5`);const data:SearchResult=await r.json();setSuggestions(data.items||[])}catch{setError('Could not load suggestions.')}finally{setLoading(false)}},250);return()=>clearTimeout(timer)},[q,uid,showAll]);
 const loadAll=async(page=1)=>{setLoading(true);setShowAll(true);setSearchPage(page);try{const r=await fetch(API+`/books/search?q=${encodeURIComponent(q)}&user_id=${uid}&page=${page}&page_size=10`);setResult(await r.json())}catch{setError('Could not load books.')}finally{setLoading(false)}};
 const recommend=async()=>{if(!recommendation.trim())return;setRecommendLoading(true);setError('');try{const r=await fetch(API+'/books/recommend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:recommendation,top_k:10,user_id:uid})});if(!r.ok)throw Error();setRecommendations((await r.json()).results||[])}catch{setError('Could not generate recommendations.')}finally{setRecommendLoading(false)}};
 const interact=async(book:Book,type:Exclude<Interaction,null>)=>{if(!uid)return;try{const r=await fetch(API+'/interactions',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:uid,work_id:book.work_id,interaction_type:type})});if(!r.ok)throw Error();const data=await r.json();const update=(items:Book[])=>items.map(x=>x.work_id===book.work_id?{...x,interaction:data.interaction}:x);setRecommendations(update);setSuggestions(update);if(result)setResult({...result,items:update(result.items)})}catch{setError('Could not update interaction.')}};
 const rate=async(book:Book,rating:number)=>{try{const r=await fetch(API+'/ratings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:uid,work_id:book.work_id,rating})});if(!r.ok)throw Error();const update=(items:Book[])=>items.map(x=>x.work_id===book.work_id?{...x,user_rating:rating}:x);setRecommendations(update);setSuggestions(update);if(result)setResult({...result,items:update(result.items)})}catch{setError('Could not save rating.')}};
 const card=(b:Book)=><article className="card" key={b.work_id}><h3>{b.title}</h3><p className="meta">{[b.first_author,b.earliest_known_publication_year,b.average_rating&&`Rating ${b.average_rating.toFixed(2)}`].filter(Boolean).join(' · ')||'Metadata unavailable'}</p><p className="description">{b.description||'No description available'}</p><div className="personal-rating"><span>Your rating</span>{[1,2,3,4,5].map(star=><button key={star} className={star<=(b.user_rating||0)?'star selected':'star'} onClick={()=>rate(b,star)} aria-label={`Rate ${star} out of 5`}>★</button>)}</div><div className="book-actions"><button className={'book-action like '+(b.interaction==='like'?'active':'')} onClick={()=>interact(b,'like')}>{b.interaction==='like'?'♥ Liked':'♡ Like'}</button><button className={'book-action dislike '+(b.interaction==='dislike'?'active':'')} onClick={()=>interact(b,'dislike')}>{b.interaction==='dislike'?'Disliked':'Dislike'}</button><button className={'book-action follow '+(b.interaction==='follow'?'active':'')} onClick={()=>interact(b,'follow')}>{b.interaction==='follow'?'✓ Following':'＋ Follow'}</button></div></article>;
 return <main className="shell"><header className="hero"><div><p className="eyebrow">Goodreads discovery</p><h1>Book RecSys</h1></div><div className="user-box"><label>Current user</label><select value={uid} onChange={e=>setUid(e.target.value)}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div></header>
 <section className="recommend-panel"><p className="eyebrow">Describe what you want to read</p><h2>Book recommendations</h2><p className="recommend-help">Describe themes, mood, genre, length, or a book you liked. This is separate from title search.</p><textarea value={recommendation} onChange={e=>setRecommendation(e.target.value)} placeholder="Example: A dark political science-fiction novel like Dune..."/><button className="recommend-button" disabled={recommendLoading||!recommendation.trim()} onClick={recommend}>{recommendLoading?'Finding books...':'Recommend books'}</button></section>
 {recommendations.length>0&&<section><div className="results-head"><h2>Recommended books</h2><span className="muted">{recommendations.length} candidates</span></div>{recommendations.map(card)}</section>}
 <section className="panel"><p className="eyebrow">Exact lookup</p><h2>Search by title or author</h2><div className="search-row"><input className="search-input" value={q} onChange={e=>{setQ(e.target.value);setShowAll(false)}} onKeyDown={e=>e.key==='Enter'&&loadAll(1)} placeholder="Search by title or author..."/><button className="filter-btn" onClick={()=>loadAll(1)}>{loading&&showAll?'Searching...':'Search'}</button>{!showAll&&q.trim()&&<div className="dropdown">{loading&&<div className="suggestion">Searching...</div>}{!loading&&suggestions.length===0&&<div className="suggestion">No matching books found.</div>}{suggestions.map(b=><button className="suggestion" key={b.work_id} onClick={()=>{setQ(b.title);loadAll(1)}}>{b.title}{b.first_author&&` by ${b.first_author}`}</button>)}{suggestions.length>0&&<button className="show-all" onClick={()=>loadAll(1)}>Show all results →</button>}</div>}</div>
 {showAll&&result&&<section><div className="results-head"><h2>Title search results</h2><span className="muted">{result.total} books found</span></div>{result.items.length?result.items.map(card):<p className="empty">No books found.</p>}{result.total_pages>1&&<div className="pagination"><button disabled={searchPage<=1||loading} onClick={()=>loadAll(searchPage-1)}>← Previous</button><span>Page {searchPage} of {result.total_pages}</span><button disabled={searchPage>=result.total_pages||loading} onClick={()=>loadAll(searchPage+1)}>Next →</button></div>}</section>}</section>{error&&<p className="error">{error}</p>}</main>;
}
