'use client';
import { useEffect, useState } from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Interaction='like'|'dislike'|'follow'|null; type User={id:string;name:string}; type Book={work_id:number;title:string;first_author?:string|null;description?:string|null;earliest_known_publication_year?:number|null;average_rating?:number|null;interaction?:Interaction}; type Result={items:Book[];page:number;page_size:number;total:number;total_pages:number};
export default function Page(){const[users,setUsers]=useState<User[]>([]),[uid,setUid]=useState(''),[query,setQuery]=useState(''),[personalized,setPersonalized]=useState(false),[result,setResult]=useState<Result|null>(null),[suggestions,setSuggestions]=useState<Book[]>([]),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
const json=async(r:Response)=>{if(!r.ok)throw Error(`${r.status}`);return r.json()};
useEffect(()=>{fetch(`${API}/users`).then(json).then((x:User[])=>{setUsers(x);if(x[0])setUid(x[0].id)}).catch(()=>setError('Backend connection failed.'))},[]);
useEffect(()=>{if(!query.trim()||personalized){setSuggestions([]);return}const t=setTimeout(()=>fetch(`${API}/books/search?q=${encodeURIComponent(query)}&user_id=${uid}&page_size=5`).then(json).then(x=>setSuggestions(x.items||[])).catch(()=>{}),250);return()=>clearTimeout(t)},[query,uid,personalized]);
const search=async(p=1)=>{if(!query.trim()||!uid)return;setBusy(true);setPage(p);setError('');try{if(personalized){const d=await json(await fetch(`${API}/bookguide`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:uid,query,top_k:10})}));const items=d.results||[];setResult({items,page:1,page_size:items.length||10,total:items.length,total_pages:1})}else setResult(await json(await fetch(`${API}/books/search?q=${encodeURIComponent(query)}&user_id=${uid}&page=${p}&page_size=10`)))}catch(e){setError(`Search failed: ${e instanceof Error?e.message:'unknown error'}`)}finally{setBusy(false)}};
const interact=async(b:Book,type:Exclude<Interaction,null>)=>{const r=await fetch(`${API}/interactions`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:uid,work_id:b.work_id,interaction_type:type})});if(r.ok)setResult(x=>x?{...x,items:x.items.map(v=>v.work_id===b.work_id?{...v,interaction:type}:v)}:x)};
const card=(b:Book)=><article className="card" key={b.work_id}><h3>{b.title}</h3><p className="meta">{[b.first_author,b.earliest_known_publication_year,b.average_rating&&`Rating ${b.average_rating.toFixed(2)}`].filter(Boolean).join(' · ')}</p><p className="description">{b.description||'No description available.'}</p><div className="book-actions"><button className={`book-action like ${b.interaction==='like'?'active':''}`} onClick={()=>interact(b,'like')}>{b.interaction==='like'?'♥ Liked':'♡ Like'}</button><button className={`book-action follow ${b.interaction==='follow'?'active':''}`} onClick={()=>interact(b,'follow')}>{b.interaction==='follow'?'✓ Following':'+ Follow'}</button></div></article>;
return <main className="shell"><header className="hero"><div><p className="eyebrow">Goodreads discovery</p><h1>Book RecSys</h1></div><div className="user-box"><label>Current user</label><select value={uid} onChange={e=>setUid(e.target.value)}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div></header><section className="search-panel"><div className="search-heading"><div><p className="eyebrow">Search library</p><h2>Find your next book</h2><p className="search-subtitle">Search normally, or let the agent tailor results to your taste.</p></div><label className="agent-toggle"><input type="checkbox" checked={personalized} onChange={e=>{setPersonalized(e.target.checked);setResult(null)}}/><span className="toggle-track"><span/></span><span><strong>Personalized</strong><small>{personalized?'Agent is on':'Agent is off'}</small></span></label></div><div className="search-row"><input className="search-input" value={query} onChange={e=>{setQuery(e.target.value);setResult(null)}} onKeyDown={e=>e.key==='Enter'&&search()} placeholder={personalized?'Try: books like Dune with political intrigue...':'Search by title or author...'}/><button className="filter-btn" disabled={busy||!query.trim()||!uid} onClick={()=>search()}>{busy?'Searching…':'Search'}</button>{!personalized&&query.trim()&&!result&&suggestions.length>0&&<div className="dropdown">{suggestions.map(b=><button className="suggestion" key={b.work_id} onClick={()=>{setQuery(b.title);search()}}>{b.title}{b.first_author&&` by ${b.first_author}`}</button>)}</div>}</div><p className="search-mode">{personalized?'Uses your profile and the BookGuide agent.':'Fast title and author lookup.'}</p></section>{result&&<section><div className="results-head"><h2>{personalized?'Personalized results':'Search results'}</h2><span className="muted">{result.total} books found</span></div>{result.items.map(card)}{!personalized&&result.total_pages>1&&<div className="pagination"><button disabled={page<=1||busy} onClick={()=>search(page-1)}>← Previous</button><span>Page {page} of {result.total_pages}</span><button disabled={page>=result.total_pages||busy} onClick={()=>search(page+1)}>Next →</button></div>}</section>}{error&&<p className="error">{error}</p>}</main>}
